### ISSUE TITLE
Modify pipeline to ignore multiple echoes 

### ISSUE THREAD

**Issue by davidmummy** [TeamXenonDuke/xenon-gas-exchange-consortium#52]
The Siemens-to-MRD converter is going to be modified to use the "SET" variable to indicate the presence of multiple echoes (see Issue 5 in that repo). However, our current GX pipeline only knows how to process the first echo. 

This GX pipeline needs to be modified to base its reconstruction on the echos where the SET header label is either "null" (backwards compatible with older files) or "1" to indicate the first echo (new MRD spec). Any fid/traj pairs with SET >=2 in the MRD can be ignored by the pipeline since we do not currently do anything with them.

**Comment by bdriehuys** [comment]
Switched to Hong. Need to pull latest MRD converter, then convert CABA072 and try it with this branch.

**Comment by Sarahhongqin** [comment]
I successfully converted the twix files, but when try the MRD file with this branch, it prompted the following error:
 File "/Users/hong/Pipeline/xenon-gas-exchange-consortium/utils/mrd_utils.py", line 390, in get_gx_data
    gas_fids_all = np.concatenate(gas_fids_all, axis=-1)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2000 and the array at index 1 has size 0

**Comment by Sarahhongqin** [comment]
The issue was resolved after Sup pushed the value changes of the set order in mrd_utils.py. It is fully ready for git pull.
