### ISSUE TITLE
Implement "aggressive" version of N4ITK to fix issue with apical coil drop-out

### ISSUE THREAD

**Issue by davidmummy** [TeamXenonDuke/xenon-gas-exchange-consortium#61]
Matt Willmering has provided us with N4ITK parameters that appear to solve issues with apical signal dropout due to coil placement, while preserving patterns in subjects that do not have this problem. 

This issue is to incorporate this updated N4ITK into our production pipeline after adequate testing. 

Any data used in subsequent publications etc. will need to be re-processed once this fix is implemented.

**Comment by davidmummy** [comment]
Please also update ventilation healthy reference distribution

**Comment by sl609** [comment]
Adding the branch that solve the issue.

**Comment by davidmummy** [comment]
Is this ready for testing? If so, please create a pull request

**Comment by bdriehuys** [comment]
We have done some fairly extensive testing to convince ourselves that this method is the way to move forward. These are described in the attached "lab report" and associated file with all the figures.

[24-09-02 Report on N4ITK Method Comparisons.pdf](https://github.com/user-attachments/files/16852651/24-09-02.Report.on.N4ITK.Method.Comparisons.pdf)
[24-09-03 Bias Field Comparison Cases Completed.pdf](https://github.com/user-attachments/files/16852652/24-09-03.Bias.Field.Comparison.Cases.Completed.pdf)
