### ISSUE TITLE
Thresholds:  enable users to choose reference thresholds but auto-detect 208 vs 218ppm

### ISSUE THREAD

**Issue by davidmummy** [TeamXenonDuke/xenon-gas-exchange-consortium#64]
Currently functionality is to just apply the 218 ppm thresholds to everything. Desired functionality:

(1) GX pipeline reads in RF excitation frequency (it already is doing this in some way, since it appears in the report)
(2) Based on frequency, either (a) use existing 218ppm values or (b) use @sl609 's new thresholds for 208ppm.

NOTE: The frequency may not always be exactly 218ppm, so will have an allowable range of ±2ppm: either 216-220ppm or 206-210ppm.

When there is no frequency specified, we can just default to 218ppm, but the system should throw a warning in the report that says "Warning: Unrecognized Excitation Frequency."

**Comment by davidmummy** [comment]
Update to my original description: 

@sl609 to provide Andrew with 208ppm numbers
AND 218ppm (which happen to be derived from 208ppm) 

Please see Sup's ATS abstract and MRM paper in work

**Comment by bdriehuys** [comment]
Agreed at IAT meeting to implement ability for users to provide their own reference distributions if desired, but maintain functionality to auto-select 218 vs 208 ppm  based on RF excitation frequency.
