### ISSUE TITLE
gradient delay values should be set in a user config file

### ISSUE THREAD

**Issue by bdriehuys** [TeamXenonDuke/xenon-gas-exchange-consortium#71]
gradient delays are a reality of radial acquisition and will vary somewhat from system to system. Currently our standard gradient delay values of -5,-5,-5 for our Prisma system are hard-coded in the pipeline. This should ideally be moved to a config file, as more people start to use or code.

**Comment by davidmummy** [comment]
Update to this issue: 
 - Gradient delays are currently able to be set in the advanced config file (although after issue #70 we will just have one config file).
 - However, the pipeline is still set to base some gradient delay choices off of "high bandwidth", "low bandwidth", etc. 
 - Goal here: remove all logic in the pipeline that sets gradient delays, anywhere. The one and only place gradient delays should be set is in the config file, and these should be required for execution. 
 
Ideally of course the user will just figure this out one time for their particular system, and then they can just copy it going forward. But the pipeline should no longer be setting the gradient delays for itself.

**Comment by davidmummy** [comment]
Assigning to @sl609 and putting in the queue.
