### ISSUE TITLE
Error reading .mrd file

### ISSUE THREAD

**Issue by YonniFriedlander** [TeamXenonDuke/xenon-gas-exchange-consortium#73]
Just getting back on the horse now and cleaning up some issues as I re-load the latest version.

In io_utils, at get_ute_mrd_files it looks for a .h5 file when loading an .mrd file.

I suggest changing it something like:

def get_dis_mrd_files(path: str) -> str:
    """Get list of gas exchange MRD files.

    Args:
        path: str directory path of MRD files
    Returns:
        str file path of MRD file
    """
    try:
        return (
            glob.glob(os.path.join(path, "**dixon***.h5"))
            + glob.glob(os.path.join(path, "**dixon***.mrd"))
            )[0]
    except:
        raise ValueError("Can't find MRD file in path.")

**Comment by davidmummy** [comment]
Hi Yonni -- thanks for flagging this. We are totally fine with using both the .h5 and the .mrd extension per your suggestion. 

We're spread thin right now though. Any chance you would want to create a branch for this at your convenience and make the code change, and then we can just check it in?

**Comment by YonniFriedlander** [comment]
Sure, happy to try but I've actually never done anything more exciting than just download code from GitHub so apologies if I do it wrong.

Yonni Friedlander | 647.967.7717 | St. Joseph's Healthcare Hamilton | Room T3218
________________________________

**Comment by davidmummy** [comment]
Excellent! And no problem we'll help work through any snags. First thing to do is just to click the "create a branch" link in GitHub (on the right of the Issue) and then download the branch to your local system. Then you can make the edits on that branch and push it back to the remote branch on Github. 

(Nobody's allowed to push to the main branch so there's no risk of accidentally overwriting our production code)
