### ISSUE TITLE
Reference 208 ans 218 PPM reference on RBC is the same

### ISSUE THREAD

**Issue by sl609** [TeamXenonDuke/xenon-gas-exchange-consortium#78]
Reference 208 ans 218 PPM reference on RBC is the same. Need to fix it

**Comment by davidmummy** [comment]
Hi @sl609 -- can you add a few more details here, please?

**Comment by sl609** [comment]
In utils/constants.py

   REFERENCE_208_PPM = {
        "title": "REFERENCE_208_PPM",
        "threshold_vent": [0.3908, 0.5741, 0.7180, 0.8413, 0.9511],
        "threshold_rbc": [0.001007, 0.002723, 0.00512, 0.00814, 0.011743],
        "threshold_membrane": [0.004170, 0.006461, 0.009249, 0.012532, 0.016309, 0.020580, 0.025344],

  REFERENCE_218_PPM = {
    "title": "REFERENCE_218_PPM",
    "threshold_vent": [0.3908, 0.5741, 0.7180, 0.8413, 0.9511],
    "threshold_rbc": [0.001007, 0.002723, 0.005120, 0.008140, 0.011743],
    "threshold_membrane": [0.003826, 0.005928, 0.008486, 0.011498, 0.014964, 0.018883, 0.023254],


We can see that the threshold of RBC is the same for both 218 and 208 ppm.
The RBC 208 ppm should be [0.0977,    0.2641,    0.4967,    0.7896,    1.1391] instead
